import Observation
import os

@Observable
public class Beholder: @unchecked Sendable {
	nonisolated public static let instance = Beholder()

	@ObservationIgnored nonisolated(unsafe) private var values: [String: Any] = [:]
	@ObservationIgnored private nonisolated let lock = OSAllocatedUnfairLock()

	nonisolated public init() {}

	nonisolated public subscript<Kind>(key: BeholderKey<Kind>) -> Kind {
		get { lock.withLock { values[key.name] as? Kind ?? key.defaultValue } }
		set { lock.withLock { values[key.name] = newValue } }
	}

	nonisolated public static subscript<Kind>(key: BeholderKey<Kind>) -> Kind {
		get { instance[key] }
		set { instance[key] = newValue }
	}

	/// Records an observation access for the given keyPath. Public so code
	/// generated by `@BeholderValue` in other modules can register per-property
	/// tracking. Not intended for direct use.
	nonisolated public func _beholderAccess<Member>(keyPath: KeyPath<Beholder, Member>) {
		access(keyPath: keyPath)
	}

	/// Wraps a mutation in an observation notification for the given keyPath.
	/// Public so code generated by `@BeholderValue` in other modules can fire
	/// per-property change notifications. Not intended for direct use.
	nonisolated public func _beholderMutation<Member>(
		keyPath: KeyPath<Beholder, Member>,
		_ mutation: () -> Void
	) {
		withMutation(keyPath: keyPath, mutation)
	}
}
